import Head from 'next/head'
import Onboarding from "@/pages/Onboarding/Onboarding";
import {ChakraProvider} from '@chakra-ui/react'
import {customTheme} from "@/styles/theme";

export default function Home() {
    return (
        <div className={"text-white"}>
            <ChakraProvider resetCSS theme={customTheme}>
                <>
                    <Head>
                        <title>quicklink</title>
                        <meta name="description" content="Generated by create next app"/>
                        <meta name="viewport" content="width=device-width, initial-scale=1"/>
                        <link rel="icon" href="/favicon.ico"/>
                    </Head>
                    <Onboarding/>
                </>
            </ChakraProvider>
        </div>
    )
}
